export default function Footer() {
  return (
    <footer className="border-t border-white/10 bg-slate-950/90">
      <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-2 px-4 py-4 text-[11px] text-slate-400 sm:flex-row">
        <p>
          © {new Date().getFullYear()} HobbyASAP. Built for curious people who
          like side quests.
        </p>
        <p className="text-[10px] text-slate-500">
          Prototype project. Plans and answers are generated by AI, so always
          adapt to your life.
        </p>
      </div>
    </footer>
  )
}
