export default function Footer() {
  return (
    <footer className="border-t border-border bg-app-bg/95">
      <div className="mx-auto flex max-w-6xl flex-col gap-3 px-4 py-4 text-[11px] text-muted sm:flex-row sm:items-center sm:justify-between">
        {/* Left side: brand + tagline */}
        <div className="space-y-1 text-center sm:text-left">
          <p className="text-[12px] font-medium text-text">
            © {new Date().getFullYear()} HobbyASAP
          </p>
          <p className="text-[11px] text-muted">
            Built for curious people.
          </p>
        </div>

        {/* Right side: links + disclaimer */}
        <div className="flex flex-col items-center gap-1 sm:items-end">
          <nav className="flex flex-wrap items-center justify-center gap-3 text-[11px] text-muted">
            <a
              href="https://github.com/luciano655dev/hobbyasap"
              target="_blank"
              rel="noreferrer"
              className="hover:text-accent hover:underline"
            >
              GitHub
            </a>
            <a
              href="https://luciano655.netlify.app"
              className="hover:text-accent hover:underline"
            >
              Portfolio
            </a>
            <a
              href="https://daykeeper.app"
              className="hover:text-accent hover:underline"
            >
              Daykeeper
            </a>
            <a
              href="https://onemoregood.vercel.app"
              className="hover:text-accent hover:underline"
            >
              OneMoreGood
            </a>
          </nav>

          <p className="text-[10px] text-muted/80 text-center sm:text-right">
            Prototype project. Plans and answers are generated by AI, so always
            adapt them to your real life.
          </p>
        </div>
      </div>
    </footer>
  )
}
