export const metadata = {
  title: "Terms of Use | HobbyASAP",
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-app-bg text-text">
      <section className="mx-auto max-w-3xl px-4 py-12">
        <p className="text-[11px] uppercase tracking-wide text-muted">Legal</p>
        <h1 className="mt-2 text-3xl font-semibold">Terms of Use</h1>
        <div className="mt-6 space-y-6 rounded-3xl border border-border bg-surface p-6 text-sm text-muted shadow-sm">
          <section className="space-y-2">
            <h2 className="text-base font-semibold text-text">1. Product nature</h2>
            <p>
              HobbyASAP is a software product for learning support and exploration.
              It is provided on an evolving basis, and features may change,
              disappear, or be interrupted at any time.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-semibold text-text">2. AI-generated content</h2>
            <p>
              Courses, lessons, plans, deep dives, and chat responses may be
              generated by AI. That content can be inaccurate, incomplete,
              repetitive, biased, or unsuitable for your goals.
            </p>
            <p>
              You are responsible for reviewing outputs before relying on them.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-semibold text-text">3. Acceptable use</h2>
            <p>
              You agree not to misuse the service, interfere with its operation,
              attempt unauthorized access, or use generated content in ways that
              violate applicable law or the rights of others.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-semibold text-text">4. No professional advice</h2>
            <p>
              HobbyASAP is not a source of legal, medical, financial, mental
              health, safety, or other professional advice. Do not use it as the
              basis for high-stakes decisions.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-semibold text-text">5. Accounts and data</h2>
            <p>
              If you create an account, you are responsible for the accuracy of
              the information you provide and for activity performed through your
              account.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-semibold text-text">6. Availability and liability</h2>
            <p>
              The service is provided on an &quot;as is&quot; and &quot;as available&quot;
              basis. To the fullest extent allowed by law, HobbyASAP disclaims
              warranties and is not liable for losses resulting from use of the
              service, generated content, outages, or inaccuracies.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-semibold text-text">7. Changes</h2>
            <p>
              These terms may be updated over time. Continued use of the product
              after changes means you accept the revised terms.
            </p>
          </section>
        </div>
      </section>
    </main>
  )
}
